language: ruby
rvm:
  - 2.2
before_script:
  - gem install jekyll
  - gem install awesome_bot
script:
  # Build jekyll to check for errors
  - bundle exec jekyll build
  # Check GitHub files for link problems
  - awesome_bot README.md --allow-dupe
