language: ruby
rvm:
  - 2.1
install:
  - gem install jekyll
  - gem install html-proofer
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site
env:
  global:
    # Speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 
