install:
  - gem install jekyll
  - gem install awesome_bot
script:
  # Build jekyll
  - bundle exec jekyll build
  # Check for link problems
  - awesome_bot README.md --allow-dupe
notifications:
  email: false
