# The URL which the site will be served from.
url: https://davison.io

# This is only needed if you are serving this site in a subdirectory.
baseurl: ""

# These files will be excluded from the generated site.
# Files or directories starting with a _ or . are automatically excluded.
exclude:
  - README.md
  - CONTRIBUTING.md

include:
  - _pages
  - .well-known

# It's good practice to set a permalink manually for each post but if not, here:
permalink: /:title/

timezone: Europe/London

#
# Site-defined variables
#

title: Craig Davison
description: Student · Minimalist · Optimist · Likes AI, music, photography, travel and other fun stuff.
at: "@davisonio"
google_analytics_tracking_id: "UA-87918631-1"
