#
# Jekyll: Handling Reading
#
exclude:
  - README.md
  - vendor

#
# Jekyll: Serving
#
url: http://davison.io
# https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
baseurl: ""

#
# Jekyll: Output Configuration
#
permalink: /:title/
timezone: Europe/London

#
# Site: Other
#

title: Craig Davison
description: ¯\_(ツ)_/¯
